### ISSUE TITLE
Can Colab Pro run it??

### ISSUE THREAD

**Issue by CarlosVecina** [camenduru/hunyuan-video-jupyter#2]
Is it needed colab pro+ or just pro?

How long does it take?

Thank you @camenduru

**Comment by WThirteen** [comment]
Thank you for raising the issues. I'd like to know too.

**Comment by camenduru** [comment]
we have this: https://x.com/camenduru/status/1864602316373938350

**Comment by busetde** [comment]
I've always got the torch.OutOfMemoryError: CUDA out of memory.
Running on A100 Colab
Any advise?

**Comment by camenduru** [comment]
we need A100 80GB

**Comment by busetde** [comment]
@camenduru - thanks for your response...
Don't have access to single GPU of A100 80GB, but have access to multi GPU of L4.
Any idea on how can the jupyter notebook provided run on multi GPU? 

Thanks

**Comment by camenduru** [comment]
@busetde, please use this https://x.com/camenduru/status/1864602316373938350 (Runpod). It seems that Colab is not capable of running this project
